# Generated by Django 3.2.25 on 2025-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base', models.CharField(max_length=30)),
                ('website_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('testid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stateorcentral', models.CharField(max_length=50)),
                ('tenthper', models.CharField(max_length=50)),
                ('twelvethper', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=50)),
                ('isdisable', models.CharField(max_length=50)),
                ('lastdate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courseid', models.CharField(max_length=30)),
            ],
        ),
    ]
